"use strict";

// Two-minute first steps, grouped by the kind of task someone is moving on to.
// Categories are checked in order and the first match wins, so more specific
// ones (email, meetings) come before broad ones (writing, study).
// Steps never mention the task itself, so they read naturally for any wording.

const STEP_CATEGORIES = [
  {
    id: "email",
    match: /\b(e-?mails?|inbox|repl(y|ies|ying)|respond|messages?|texts?|whatsapp|slack|dms?|write back|get back to)\b/,
    steps: [
      "Open your inbox and find the one message you need to answer.",
      "Open a new draft and type just the greeting.",
      "Write the subject line, nothing else yet.",
      "Type the first sentence of your reply, even if it's clumsy.",
      "Find the message and pin or star it so it's waiting for you.",
      "Write three bullet points of what you want to say.",
      "Put the recipient's name in a fresh draft.",
      "Type “Thanks for your message” and see where it goes.",
      "Close every tab except the one you'll write in.",
      "Read the message you're replying to once, slowly.",
      "Write the sign-off first, then go back up to the top.",
      "Mute notifications for the next half hour.",
      "Archive three messages you don't need, to warm up.",
      "Say out loud what you want the reply to say, in one sentence.",
      "Search for the person's name to bring up the thread.",
      "Write the reply as if it were a quick text. You can tidy it later.",
      "Jot down the one question you need answered.",
      "Scroll to the latest message in the thread and read it.",
      "Set a two-minute timer and type without editing.",
      "Write the hardest sentence first, badly.",
    ],
  },
  {
    id: "meeting",
    match: /\b(meetings?|presentations?|present(ing)?|slides?|deck|interviews?|stand-?up|pitch|zoom|teams call|webinar|workshop|1:1|one-to-one|agenda|speech)\b/,
    steps: [
      "Open the invite and read the agenda.",
      "Write the one thing you want to get out of it.",
      "Open the slides and look at the first one only.",
      "Jot down one question you could ask.",
      "Find the link or room and keep it open.",
      "Check your camera and microphone.",
      "Write three words that sum up your main point.",
      "Say your opening sentence out loud.",
      "Fill a glass of water to bring with you.",
      "Open your notes from last time.",
      "Write down who'll be there.",
      "Make a new slide with just a title on it.",
      "Close anything you won't want on screen.",
      "Read the last email about it.",
      "Finish this sentence: “By the end, I want…”",
      "Put your phone on silent.",
      "Sketch the order of your points as three boxes.",
      "Rehearse the first thirty seconds once.",
      "Open a fresh note with today's date as the title.",
      "Tidy what's behind you on camera.",
    ],
  },
  {
    id: "call",
    match: /\b(call|calls|calling|phone|ring|dial|voicemail|appointments?|booking|gp|dentist|doctors?)\b/,
    steps: [
      "Find the number and put it into your phone.",
      "Write down the one thing you need from this call.",
      "Open your calendar so it's ready if you need to book something.",
      "Put a pen and paper next to your phone.",
      "Write the first sentence you'll say when they answer.",
      "Find a quiet spot and sit down with your phone.",
      "Check their opening hours.",
      "Get any reference number or account details in front of you.",
      "Pour a glass of water to have during the call.",
      "Say your opening line out loud once.",
      "Check your phone is charged, or plug it in.",
      "Write their name at the top of a note.",
      "Jot down two questions you want to ask.",
      "Open the page or email with their contact details.",
      "Write down when you're free over the next week.",
      "Press call. You only have to say hello.",
      "Close the door or move somewhere you can hear well.",
      "Write what you'll say if you get voicemail.",
      "Note the time you're calling, so you have a record.",
      "Stand up, stretch, then pick up your phone.",
    ],
  },
  {
    id: "code",
    match: /\b(code|coding|program(ming)?|debug(ging)?|bugs?|refactor(ing)?|deploy(ing)?|commit|pull request|pr|repo|github|implement(ing)?|features?|functions?|api|script|compile|unit tests?|python|javascript|typescript|rust|sql)\b/,
    steps: [
      "Open the project and run it once.",
      "Run the tests and read the first failure.",
      "Open the file you'll be working in.",
      "Write a one-line comment saying what you'll do next.",
      "Pull the latest changes.",
      "Create a new branch for the task.",
      "Read the issue or ticket from top to bottom.",
      "Write the name of the function you'll need, with an empty body.",
      "Reproduce the bug once and note what happens.",
      "Write a failing test, even a rough one.",
      "Search the codebase for the main word in your task.",
      "Look at the last commit to remember where you were.",
      "Add a log line where you think the problem is.",
      "Close every unrelated tab and file.",
      "Write three lines of to-do in a scratch file.",
      "Open the docs for the library you'll need.",
      "Rename one unclear variable you spot.",
      "Explain the problem out loud, as if to a rubber duck.",
      "Check what's uncommitted and stash anything left over.",
      "Start the dev server and open it in the browser.",
    ],
  },
  {
    id: "creative",
    match: /\b(draw(ing)?|paint(ing)?|sketch(ing)?|design(ing)?|music|songs?|guitar|piano|drums?|violin|cello|ukulele|instrument|compos(e|ing|ition)|craft(ing)?|knit(ting)?|sew(ing)?|crochet|photo(s|graphy)?|video|film|animat(e|ion)|illustrat(e|ion)|pottery|sing(ing)?)\b/,
    steps: [
      "Lay out your materials.",
      "Draw one line. Any line.",
      "Tune or warm up your instrument.",
      "Open a blank canvas or page.",
      "Play one scale slowly.",
      "Look at something you made before, for a minute.",
      "Pick one colour to start with.",
      "Make a two-minute sketch you'll throw away.",
      "Put on music that puts you in the mood.",
      "Open the project file.",
      "Sharpen your pencils or rinse a brush.",
      "Write down one idea, however small.",
      "Hum or play the first bar.",
      "Clear space on the table.",
      "Take one photo of anything nearby.",
      "Thread the needle or cast on one stitch.",
      "Copy a shape from something in the room.",
      "Set up your stand, easel or chair.",
      "Look through your references for a minute.",
      "Make one mark you're allowed to hate.",
    ],
  },
  {
    id: "admin",
    match: /\b(pay(ing)?|bills?|tax(es)?|budget(ing)?|invoices?|expenses?|forms?|paperwork|apply|application|renew(al)?|bank(ing)?|accounts?|admin|insurance|receipts?|mortgage|rent|pension|council|passport|visa|contracts?|claims?|refund|finances?|benefits)\b/,
    steps: [
      "Find the letter or email about it.",
      "Open your banking app.",
      "Put all the paperwork in one pile.",
      "Find the reference number and copy it somewhere handy.",
      "Open the form and fill in your name.",
      "Write down the deadline.",
      "Log in to the website, and nothing more.",
      "Make a folder for it on your computer.",
      "Find your card or account details.",
      "Read the first page of the form.",
      "Photograph the document you'll need.",
      "Write a three-item checklist of what it needs.",
      "Open a spreadsheet and type the column headings.",
      "Find last time's version to copy from.",
      "Put the due date in your calendar.",
      "Gather three receipts.",
      "Check you can still log in.",
      "Fill in the first box. Just one.",
      "Look up the helpline number in case you get stuck.",
      "Pour a drink and sit down with the paperwork.",
    ],
  },
  {
    id: "errands",
    match: /\b(shop(ping)?|groceries|grocery|supermarket|buy|order|errands?|pick up|collect|post office|parcels?|returns?|pharmacy|prescription|chemist)\b/,
    steps: [
      "Write the first three things on your list.",
      "Find your bags and put them by the door.",
      "Check the opening hours.",
      "Open the fridge and note what's missing.",
      "Put your shoes and coat on.",
      "Find your keys, wallet and phone.",
      "Open the shopping app and add one thing to the basket.",
      "Put the parcel by the door.",
      "Check the bus times or where you'll park.",
      "Write your stops in order.",
      "Look up the address.",
      "Put your list in your pocket.",
      "Check your card is in your wallet.",
      "Find the receipt for the return.",
      "Check the cupboards for what you're out of.",
      "Put a bottle of water in your bag.",
      "Write down the one thing you mustn't forget.",
      "Open the delivery slots and pick one.",
      "Plug your phone in while you get ready.",
      "Step outside the front door.",
    ],
  },
  {
    id: "planning",
    match: /\b(plan(ning)?|to-?dos?|schedule|prioriti[sz]e|calendar|diary|organi[sz]e (my|the) (day|week|time)|week ahead|goals?)\b/,
    steps: [
      "Write down everything on your mind, as a list.",
      "Open your calendar and look at today.",
      "Circle the one thing that matters most.",
      "Write tomorrow's date at the top of a page.",
      "Pick three tasks for today and no more.",
      "Cross off anything already done.",
      "Open your to-do list.",
      "Move one task to another day.",
      "Write the next meeting's time on a sticky note.",
      "Write the first step of the biggest task.",
      "Delete one task you're never going to do.",
      "Look at what's due this week.",
      "Block out one hour in your calendar.",
      "Write a list of what you've already done.",
      "Sort the list into now, later and never.",
      "Check your messages for anything urgent.",
      "Write down the next deadline.",
      "Choose the first thing you'll do after this.",
      "Put your list somewhere you'll see it.",
      "Group three similar tasks together.",
    ],
  },
  {
    id: "study",
    match: /\b(study(ing)?|revis(e|ing|ion)|homework|exams?|tests?|quiz|read(ing)?|books?|learn(ing)?|course|lectures?|class(es)?|flashcards?|research|assignments?|coursework|lessons?|tutorials?|textbook|practi[cs](e|ing))\b/,
    steps: [
      "Open the book or notes to the right page.",
      "Read one paragraph and underline one thing.",
      "Write down one thing you remember from last time.",
      "Make three flashcards.",
      "Open the lecture or video and press play.",
      "Read the first question.",
      "Clear the desk except for what you need.",
      "Write today's date and the topic at the top of a page.",
      "Look over the chapter headings for a minute.",
      "Put your phone in another room.",
      "Explain one idea out loud in your own words.",
      "Find the assignment and read what's actually being asked.",
      "Copy out one key definition.",
      "Test yourself on one flashcard.",
      "Skim the summary at the end of the chapter.",
      "Write one question you want answered today.",
      "Find a pen that works.",
      "Set out a glass of water next to your notes.",
      "Look up one word you didn't understand.",
      "Redo one example from your notes.",
    ],
  },
  {
    id: "writing",
    match: /\b(write|writing|draft(ing)?|essays?|reports?|blog|articles?|docs?|documents?|proposals?|letters?|story|stories|thesis|dissertation|paper|post|newsletter|chapters?|edit(ing)?|proofread(ing)?|journal)\b/,
    steps: [
      "Open the document and put your cursor where you'll start.",
      "Write one messy sentence. It's allowed to be bad.",
      "Type the title, even a placeholder.",
      "Write three headings for the sections.",
      "Read the last paragraph you wrote.",
      "Set a two-minute timer and write without stopping.",
      "Sum up the main point in one sentence.",
      "Write the sentence you're most sure about.",
      "Paste your notes in so everything's in one place.",
      "Start a new document called “rough draft”.",
      "Describe what you're writing as if texting a friend.",
      "Write down one question the piece needs to answer.",
      "Fix one typo you spot.",
      "Write the first line of the ending.",
      "Open your notes next to the document.",
      "Write “The point is…” and finish the sentence.",
      "Read the brief or instructions once.",
      "Highlight the paragraph you'll work on next.",
      "List what you already know about it.",
      "Dictate one sentence into your phone.",
    ],
  },
  {
    id: "cooking",
    match: /\b(cook(ing)?|bake|baking|dinner|lunch|breakfast|supper|meals?|meal prep|recipe|food)\b/,
    steps: [
      "Wash your hands and roll up your sleeves.",
      "Get the pan out and put it on the hob.",
      "Fill the kettle and switch it on.",
      "Take out every ingredient and line them up.",
      "Read the recipe through once.",
      "Peel one onion.",
      "Clear a space on the counter.",
      "Turn the oven on to heat up.",
      "Put a pot of water on to boil.",
      "Rinse the vegetables.",
      "Open the fridge and pick one thing to use.",
      "Find the chopping board and a sharp knife.",
      "Put on a podcast or some music.",
      "Empty the sink so you have room.",
      "Measure out the first ingredient.",
      "Get out the plates you'll eat from.",
      "Pour a little oil into the pan.",
      "Write down what you'll make, if you haven't decided.",
      "Check you have the main ingredient.",
      "Measure out the rice or pasta.",
    ],
  },
  {
    id: "cleaning",
    match: /\b(clean(ing)?|tidy(ing)?|wash(ing)?|dishes|laundry|vacuum(ing)?|hoover(ing)?|declutter(ing)?|organi[sz]e|sort|mop(ping)?|dust(ing)?|bins?|rubbish|trash|recycling|bedroom|kitchen|bathroom|fold(ing)?|put away|iron(ing)?|chores?|make (the|my) bed)\b/,
    steps: [
      "Put on music you like.",
      "Pick up five things and put them where they belong.",
      "Fill the sink with hot, soapy water.",
      "Grab a bin bag and throw away three things.",
      "Clear one surface completely.",
      "Put a load of washing in.",
      "Open a window.",
      "Wipe one counter.",
      "Gather all the cups and take them to the kitchen.",
      "Set a two-minute timer and tidy until it rings.",
      "Make the bed.",
      "Get the vacuum out and plug it in.",
      "Pick the smallest corner and start there.",
      "Empty the top rack of the dishwasher.",
      "Pick up everything on the floor in one spot.",
      "Fold three pieces of clothing.",
      "Take one thing to the room it belongs in.",
      "Spray the cleaner and wipe one patch.",
      "Put on gloves or roll up your sleeves.",
      "Take out the bin.",
    ],
  },
  {
    id: "exercise",
    match: /\b(exercise|work ?out|gym|run(ning)?|jog(ging)?|walk(ing)?|yoga|pilates|stretch(ing)?|swim(ming)?|cycl(e|ing)|bike|training|lift(ing)?|weights|sports?|football|tennis|climb(ing)?|danc(e|ing)|physio)\b/,
    steps: [
      "Put on your trainers.",
      "Change into your workout clothes.",
      "Fill your water bottle.",
      "Roll out the mat.",
      "Do ten slow shoulder rolls.",
      "Pick the playlist you'll listen to.",
      "Step outside the front door.",
      "Stretch your calves for thirty seconds each side.",
      "March on the spot for a minute.",
      "Pack your gym bag.",
      "Find the workout video and have it ready.",
      "Do five squats.",
      "Put your headphones on.",
      "Lay your kit out on the floor.",
      "Walk to the end of your road.",
      "Start your tracker or app.",
      "Do a minute of gentle neck and wrist circles.",
      "Put your keys and phone by the door.",
      "Drink a glass of water.",
      "Choose the route you'll take.",
    ],
  },
  {
    id: "ready",
    match: /\b(get(ting)? ready|shower|bath|dress(ed)?|leave|leaving|go out|head out|commute|pack(ing)?|school run|go to (work|school|uni|the office)|get up|morning routine)\b/,
    steps: [
      "Put your shoes by the door.",
      "Get your clothes out.",
      "Turn the shower on.",
      "Find your keys, wallet and phone.",
      "Brush your teeth.",
      "Check the weather.",
      "Put your bag by the door.",
      "Write the time you need to leave on a sticky note.",
      "Fill your water bottle.",
      "Put your coat on the back of a chair.",
      "Plug in your phone while you get ready.",
      "Pick an outfit and lay it on the bed.",
      "Check the route or travel times.",
      "Put three things you need into your bag.",
      "Wash your face.",
      "Set an alarm for when you need to leave.",
      "Put your charger in your bag.",
      "Put on one sock. Then the other.",
      "Open the curtains.",
      "Pack a snack.",
    ],
  },
  {
    id: "sleep",
    match: /\b(bed|bedtime|sleep|nap|night routine)\b/,
    steps: [
      "Put your phone on charge across the room.",
      "Brush your teeth.",
      "Dim the lights.",
      "Get into your pyjamas.",
      "Set your alarm for tomorrow.",
      "Fill a glass of water for your bedside.",
      "Write down anything on your mind.",
      "Close the curtains.",
      "Wash your face.",
      "Put tomorrow's clothes out.",
      "Switch off the screens in the room.",
      "Turn the covers down.",
      "Open the window a crack.",
      "Pick a book to read in bed.",
      "Sit on the bed and take three slow breaths.",
      "Lock the front door.",
      "Switch on a bedside lamp and turn off the main light.",
      "Put on something cosy.",
      "Write one thing that went well today.",
      "Put your glasses where you'll find them in the morning.",
    ],
  },
  {
    id: "general",
    match: /.*/,
    steps: [
      "Clear a small space to work in.",
      "Open the thing you need, and nothing else.",
      "Write down the very first physical action.",
      "Set a timer for two minutes and just begin.",
      "Put your phone face down, out of reach.",
      "Get a glass of water and sit where you'll work.",
      "Say out loud what you're about to do.",
      "Gather the one tool you'll need first.",
      "Write the task at the top of a page.",
      "Do the smallest, silliest part first.",
      "Close every tab you won't need.",
      "Look at the task for one minute without judging it.",
      "Put on music that helps you focus.",
      "Go and stand where you'll do it.",
      "Pick up the thing you need to work on.",
      "Write one sentence about what “done” looks like.",
      "Do it badly for two minutes.",
      "Find where you left off last time.",
      "Put everything you need within arm's reach.",
      "Tell someone what you're about to start.",
      "Open a window, take three breaths, then start.",
      "Ask yourself what the next tiny step is, and do just that.",
      "Move one thing that's in the way.",
      "Write three steps, then do the first.",
      "Sit up, roll your shoulders, and begin.",
      "Stick a note with the task where you can see it.",
      "Start in the middle if the beginning feels hard.",
      "Do the part you'd least mind doing.",
      "Turn off notifications for the next half hour.",
      "Find the instructions or notes for it.",
      "Picture the first thirty seconds, then do them.",
      "Switch on a lamp to mark the start.",
      "Jot down anything that's worrying you, then set it aside.",
      "Change into something comfortable for it.",
      "Spend two minutes on it. You're allowed to stop after that.",
      "Lay out what you need in the order you'll use it.",
      "Choose a spot, sit down, and take one slow breath.",
      "Wash your hands, then begin.",
      "Open a blank note and write the first thing that comes to mind.",
      "Set out what you need, then sit with it for a moment.",
    ],
  },
];

const STEP_HISTORY_KEY = "segue.steps";

function stepCategory(task) {
  const text = (task ?? "").toLowerCase();
  if (!text.trim()) return STEP_CATEGORIES.at(-1);
  return STEP_CATEGORIES.find((category) => category.match.test(text));
}

// Steps are drawn from a shuffled bag per category: every step is shown once
// before any repeats, and the bag is remembered between visits.
function suggestStep(task, avoid) {
  const category = stepCategory(task);
  let history = {};
  try {
    history = JSON.parse(localStorage.getItem(STEP_HISTORY_KEY)) ?? {};
  } catch {
    // Without storage we still pick at random; repeats are just more likely.
  }

  let shown = new Set(history[category.id] ?? []);
  let options = category.steps.filter((step) => !shown.has(step));
  if (options.length === 0) {
    shown = new Set();
    options = category.steps.filter((step) => step !== avoid);
  }

  const step = options[Math.floor(Math.random() * options.length)];
  shown.add(step);
  history[category.id] = [...shown];
  try {
    localStorage.setItem(STEP_HISTORY_KEY, JSON.stringify(history));
  } catch {}
  return step;
}
